query getParentIeObject($currentObjectIri: String!) {
	graph_intellectual_entity(
		where: {
			id: { _eq: $currentObjectIri }
			dctermsFormat: { dcterms_format: { _in: ["videofragment", "audiofragment"] } }
		}
	) {
		isPartOf {
			id
			schema_identifier
			dcterms_available
			schema_date_created
			schema_date_published
			schema_description
			schemaNames(where: { is_ai_generated: { _eq: false } }) {
				schema_name
				is_ai_generated
			}
			dctermsFormat {
				dcterms_format
			}
			schemaDuration {
				schema_duration
			}
			schemaLicense {
				schema_license
			}
			schemaThumbnail {
				schema_thumbnail_url
			}
			schemaMaintainer {
				id
				org_identifier
				ha_org_sector
				skos_pref_label
				organizationSlug {
					slug
				}
			}
		}
	}
}
