export default {
	took: 12,
	timed_out: false,
	_shards: { total: 8, successful: 8, skipped: 0, failed: 0 },
	hits: {
		total: { value: 14, relation: 'eq' },
		max_score: 1.0,
		hits: [
			{
				_index: 'or-154dn75',
				_type: '_doc',
				_id: '8s4jm2514q',
				_score: 1.0,
				_source: {
					schema_in_language: null,
					dcterms_available: '2015-09-19T12:08:24',
					schema_creator: null,
					schema_identifier: '8s4jm2514q',
					schema_description: null,
					schema_publisher: null,
					schema_duration: '01:01:59',
					schema_abstract: null,
					premis_identifier: 'umatic_107',
					schema_genre: null,
					schema_date_published: null,
					schema_license: [
						'VIAA-ONDERWIJS',
						'VIAA-ONDERZOEK',
						'VIAA-INTRA_CP-CONTENT',
						'VIAA-INTRA_CP-METADATA-ALL',
						'VIAA-PUBLIEK-METADATA-LTD',
					],
					schema_date_created: '1982-01-01',
					schema_contributor: null,
					schema_maintainer: [{ schema_identifier: 'OR-154dn75' }],
					dcterms_format: 'video',
					schema_name: 'CGSO. De mannenbeweging - mannenemancipatie - 1982',
				},
			},
			{
				_index: 'or-1v5bc86',
				_type: '_doc',
				_id: '4f1mg9x363',
				_score: 1.0,
				_source: {
					schema_in_language: null,
					dcterms_available: '2020-10-22T14:53:35',
					schema_creator: { Maker: ['filmmaker | Ballaux, Joachim'] },
					schema_identifier: '4f1mg9x363',
					schema_description:
						"Een film gemaakt naar aanleiding van het project 'Kraanlei wordt Kraanwei' tijdens de Patersholfeesten van 2018. Een film over het leven op de boerderij waarbij de tractor centraal staat.",
					schema_publisher: null,
					schema_duration: '00:02:22',
					schema_abstract: null,
					premis_identifier: 'VI-0011-0004',
					schema_genre: null,
					schema_date_published: null,
					schema_license: [
						'CP-WEBSITE',
						'VIAA-INTRA_CP-CONTENT',
						'VIAA-INTRA_CP-METADATA-ALL',
						'VIAA-ONDERWIJS',
						'VIAA-ONDERZOEK',
						'VIAA-PUBLIEK-METADATA-LTD',
					],
					schema_date_created: '2018-01-01',
					schema_contributor: null,
					schema_maintainer: [{ schema_identifier: 'OR-1v5bc86' }],
					dcterms_format: 'video',
					schema_name: 'Op de boerderij',
				},
			},
			{
				_index: 'or-1v5bc86',
				_type: '_doc',
				_id: 'm901z6jj6k',
				_score: 1.0,
				_source: {
					schema_in_language: null,
					dcterms_available: '2020-11-30T23:08:26',
					schema_creator: {
						Maker: [
							'opdrachtgever | Huis van Alijn',
							'geïnterviewde | Korittnig, Daniel',
							'producent | Van Herwegen, Kobe',
							'producent | Plas, Peter',
						],
					},
					schema_identifier: 'm901z6jj6k',
					schema_description:
						"Interview met Daniel Korittnig van Circus Barones in het kader van de tentoonstelling 'Circus onderweg'.\nDaniel vertelt hoe Circus Barones is begonnen en wie er allemaal werkt. Hij licht zijn eigen carrière toe en legt uit hoe het leven in een circus eruit ziet. Daniel somt op welke talen hij allemaal spreekt. Verder vertelt hij welke aanpassingen ze moeten doen door het coronavirus. Hij sluit af door te zeggen dat hij heel graag het circus van zijn vader wil blijven verderzetten.",
					schema_publisher: null,
					schema_duration: '00:02:58',
					schema_abstract: null,
					premis_identifier: 'DB-2020-004-006',
					schema_genre: null,
					schema_date_published: null,
					schema_license: [
						'CP-WEBSITE',
						'VIAA-INTRA_CP-CONTENT',
						'VIAA-INTRA_CP-METADATA-ALL',
						'VIAA-ONDERWIJS',
						'VIAA-ONDERZOEK',
						'VIAA-PUBLIEK-METADATA-LTD',
					],
					schema_date_created: '2020-01-01',
					schema_contributor: null,
					schema_maintainer: [{ schema_identifier: 'OR-1v5bc86' }],
					dcterms_format: 'video',
					schema_name: 'Interview met Daniel van Circus Barones, 2020',
				},
			},
			{
				_index: 'or-2z12p11',
				_type: '_doc',
				_id: '4x54f45b8k',
				_score: 1.0,
				_source: {
					schema_in_language: null,
					dcterms_available: '2021-01-14T21:32:11',
					schema_creator: {
						Maker: [
							'interviewer | De Baerdemaeker, Marieke |',
							'geïnterviewde | Calle, Linda | Gent',
							'producent | Danse La Pluie',
							'opdrachtgever | MIAT',
						],
					},
					schema_identifier: '4x54f45b8k',
					schema_description:
						"Interview met Linda Calle in het kader van het project 'Hun werk, hun leven. Getuigenissen uit de Gentse textielwereld 1950-2010'.",
					schema_publisher: null,
					schema_duration: '01:23:08',
					schema_abstract: null,
					premis_identifier: 'VI00006-026',
					schema_genre: null,
					schema_date_published: null,
					schema_license: [
						'CP-WEBSITE',
						'VIAA-INTRA_CP-CONTENT',
						'VIAA-INTRA_CP-METADATA-ALL',
						'VIAA-ONDERWIJS',
						'VIAA-ONDERZOEK',
						'VIAA-PUBLIEK-METADATA-LTD',
					],
					schema_date_created: '2017-12-15',
					schema_contributor: null,
					schema_maintainer: [{ schema_identifier: 'OR-2z12p11' }],
					dcterms_format: 'video',
					schema_name:
						'Interview met Linda Calle over haar werk in de Gentse textielindustrie',
				},
			},
			{
				_index: 'or-2z12p11',
				_type: '_doc',
				_id: 'bc3st99v1z',
				_score: 1.0,
				_source: {
					schema_in_language: null,
					dcterms_available: '2019-04-26T10:00:36',
					schema_creator: { Maker: ['producent | Danse La Pluie | Gent'] },
					schema_identifier: 'bc3st99v1z',
					schema_description:
						'Demonstratie van de werking van de lettergietmachine van het merk Monotype, in het drukatelier van het MIAT (nu Industriemuseum).',
					schema_publisher: null,
					schema_duration: '00:01:44',
					schema_abstract: null,
					premis_identifier: 'VI00013-005',
					schema_genre: null,
					schema_date_published: null,
					schema_license: [
						'CP-WEBSITE',
						'VIAA-INTRA_CP-CONTENT',
						'VIAA-INTRA_CP-METADATA-ALL',
						'VIAA-ONDERWIJS',
						'VIAA-ONDERZOEK',
						'VIAA-PUBLIEK-METADATA-LTD',
					],
					schema_date_created: '2010-01-01',
					schema_contributor: null,
					schema_maintainer: [{ schema_identifier: 'OR-2z12p11' }],
					dcterms_format: 'video',
					schema_name: 'Lettergietmachine Monotype, 1960',
				},
			},
			{
				_index: 'or-4q7qp5p',
				_type: '_doc',
				_id: 'qsmc8rcf8b',
				_score: 1.0,
				_source: {
					schema_in_language: null,
					dcterms_available: '2019-11-14T16:07:00',
					schema_creator: null,
					schema_identifier: 'qsmc8rcf8b',
					schema_description:
						"Diest investeert fors in verkeersveiligheid, nieuw zwembad en ANPR-camera'sextra politiecontroles aan asielcentrum Dormaal na brand in asielcentrum BilzenVandalen slaan opnieuw toe in scholen in onze regio: Sint-Angela Instituut in Tildonk kort en klein geslagen.",
					schema_publisher: { Publisher: ['TV Limburg'] },
					schema_duration: '00:27:24',
					schema_abstract: null,
					premis_identifier: '20191112-293-2272',
					schema_genre: null,
					schema_date_published: null,
					schema_license: [
						'VIAA-ONDERWIJS',
						'VIAA-ONDERZOEK',
						'VIAA-INTRA_CP-CONTENT',
						'VIAA-INTRA_CP-METADATA-ALL',
						'VIAA-PUBLIEK-METADATA-LTD',
					],
					schema_date_created: '2019-11-12',
					schema_contributor: null,
					schema_maintainer: [{ schema_identifier: 'OR-4q7qp5p' }],
					dcterms_format: 'video',
					schema_name: 'Nieuws dinsdag 12 november',
				},
			},
			{
				_index: 'or-7h1dk9t',
				_type: '_doc',
				_id: 'x921c4s60t',
				_score: 1.0,
				_source: {
					schema_in_language: null,
					dcterms_available: '2021-12-10T22:33:37',
					schema_creator: {
						Maker: ['Vlaams Parlement'],
						Archiefvormer: ['Vlaams Parlement'],
					},
					schema_identifier: 'x921c4s60t',
					schema_description:
						'Motie van Mieke Schauvliege, Freya Van den Bossche, Björn Rzoska, Bruno Tobback, Imade Annouri en Hannes Anaf tot uitoefening van het recht van onderzoek naar de aanpak van de met PFOS vervuilde gronden op de Oosterweelwerf en de gevolgen voor de volksgezondheid\n844 (2020-2021) nr. 1\nVerslaggevers: Tinne Rombouts, Mieke Schauvliege en Willem-Frederik Schiltz\nHoorzitting met 3M Belgium bvba\n25 (2021-2022)',
					schema_publisher: null,
					schema_duration: '04:35:08',
					schema_abstract: null,
					premis_identifier: '1577020',
					schema_genre: null,
					schema_date_published: '2021-12-03',
					schema_license: [
						'VIAA-ONDERWIJS',
						'VIAA-ONDERZOEK',
						'VIAA-INTRA_CP-CONTENT',
						'VIAA-INTRA_CP-METADATA-ALL',
						'VIAA-PUBLIEK-METADATA-LTD',
						'VIAA-PUBLIEK-METADATA-ALL',
						'VIAA-PUBLIEK-CONTENT',
						'CC-BY-SA-CONTENT',
					],
					schema_date_created: '2021-12-03',
					schema_contributor: null,
					schema_maintainer: [{ schema_identifier: 'OR-7h1dk9t' }],
					dcterms_format: 'video',
					schema_name: 'Onderzoekscommissie PFAS-PFOS 03-12-2021, 08u56',
				},
			},
			{
				_index: 'or-rf5kf25',
				_type: '_doc',
				_id: 'q23qv3wp5b',
				_score: 1.0,
				_source: {
					schema_in_language: null,
					dcterms_available: '2016-11-06T17:02:18',
					schema_creator: null,
					schema_identifier: 'q23qv3wp5b',
					schema_description: null,
					schema_publisher: null,
					schema_duration: '00:00:05',
					schema_abstract: null,
					premis_identifier: 'WV11260902',
					schema_genre: 'trailer',
					schema_date_published: '2016-11-06',
					schema_license: null,
					schema_date_created: '2016-11-06',
					schema_contributor: null,
					schema_maintainer: [{ schema_identifier: 'OR-rf5kf25' }],
					dcterms_format: 'video',
					schema_name: 'STIHL: SV DUBLIN ZOO/STIHL zoo na',
				},
			},
			{
				_index: 'or-rf5kf25',
				_type: '_doc',
				_id: '8911p09j1g',
				_score: 1.0,
				_source: {
					schema_in_language: null,
					dcterms_available: '2020-08-28T11:48:11',
					schema_creator: { productionCompany: ['Roses Are Blue'] },
					schema_identifier: '8911p09j1g',
					schema_description:
						"Humaninterestprogramma waarin Siska Schoeters op een openhartige manier gevoelige thema's bespreekbaar maakt. Elke aflevering nodigt zij een groep mensen uit waar we stiekem heel veel vragen over hebben, maar die we niet zelf in hun gezicht durven stellen.",
					schema_publisher: null,
					schema_duration: '00:39:52',
					schema_abstract:
						'In Vlaanderen leven ongeveer 1800 mensen met de diagnose van jongdementie. \nDementie is meer dan vergeten alleen. Dat zeggen Christine, Roger, Marleen, John en Paul. Samen met hun mantelzorger antwoorden ze op vragen als: "Kan je genezen?" en "Heb je al aan euthanasie gedacht?". \nMarleen noemt het een \'klotenziekte\' maar toch blijft ze positief en wil ze nog zoveel mogelijk van het leven genieten. Dat ondervindt Siska in een fietstocht die het Ventiel, een vrijwilligersorganisatie voor mensen met jongdementie, organiseert.\n\nRoger Vanparijs  (66) Marleen Snauwaert (65)\nRoger kreeg in 2007 de diagnose van frontotemporale jongdementie. Op de hersenscan zagen de artsen dat het rechterdeel vooraan in de hersenen helemaal zwart geworden was en eigenlijk afgestorven was. Volgens zijn vrouw, Marleen is zijn karakter ook heel erg veranderd. Ook dat is een typisch verschijnsel van frontotemporale jongdementie. Roger is verbaal ook heel agressief en kan snel uitvliegen. \nRoger was werfleider bij ruwbouwprojecten. Maar op een bepaald moment begon hij fouten te maken in de job. Ook leren werken met Excel lukte niet. Omdat hij niet begreep wat er aan de hand was, zakte hij weg in een depressie. Na vijf lange jaren zoeken wat er aan de hand was, ontdekte een neuroloog dat het een vorm van jongdementie was.\n\nPaul Goossens  (67) en Katelijne Lefevre (60) \nPaul kreeg vier jaar geleden een diagnose van parkinson. Niet veel later zei de neuroloog dat hij ook alzheimer had. Paul vindt het heel belangrijk om te praten over alzheimer. Volgens hem denken de meeste mensen dat je, eens je de diagnose gekregen hebt, niks meer kan en je een oud persoon bent die gewoon in een zetel zit en een plantje is. Het is voor Paul heel belangrijk om te ontkrachten.\nPaul moest kiezen tussen medicatie voor parkinson of voor alzheimer, omdat die elkaar kunnen beïnvloeden. Hij heeft gekozen voor de remmers voor alzheimer. “Ik wil liever mijn hersenen langer houden. Met fysische beperkingen kan ik beter om."\n\nMarleen Peperstraete (62) en Dirk Cecabooter (64) \nMarleen heeft de diagnose van alzheimer gekregen toen ze 57 jaar was. Eerst dachten de artsen dat ze een depressie had. Ze maakte fouten op haar werk, en niet veel later is ze volledig gestopt met werken. Na vele onderzoeken kreeg ze de diagnose Alzheimer. \nNaast het feit dat Marleen veel zaken vergeet, is het meest uitgesproken symptoom van de ziekte bij haar dat ze geen dieptezicht meer heeft. Ze kan dus maar heel moeilijk schrijven, haar schoenen aandoen, wandelen... Het is heel duidelijk dat Marleen en Dirk elkaar graag zien. Dirk is gestopt met werken om zijn vrouw te kunnen verzorgen. Marleen vergeet heel veel, maar het gsm-nummer van Dirk kan ze nog zo uit het hoofd opzeggen. \n\nChristine Pluymers  (70) en Jean-Pierre Vanden Waeyenberg (65)\nChristine kreeg 3 jaar geleden de diagnose van alzheimer. Maar de ziekte sluimerde al langer, daarom kreeg ze nog de diagnose van jongdementie. Voor Christine is het moeilijk om te weten welke dag het is. Ook het uur lezen is heel moeilijk geworden. Het moeilijkste voor Christine is ontdekken dat ze niet meer kan schrijven omdat ze haar hele leven leerkracht Nederlands (en dodsdienst) is geweest. Haar spelling ging al een tijdje achteruit, maar om nu echt niet meer de coördinatie te hebben om te kunnen schrijven, dat was een zware klap.  \nAlleen blijven zonder haar man Jean-Pierre begint moeilijk te worden. Hij schrijft wel altijd op een briefje waar hij naartoe gaat, maar soms vergeet ze dat te lezen of leest ze het en vergeet ze het snel weer. Hierdoor raakt ze in paniek als hij er niet is.\n\nJohn  Buck (44) & Cindy De Buck (46)\nJohn heeft de diagnose van frontotemporale jongdementie gekregen. Hij is niet getrouwd, dus zijn zus Cindy zorgt voor hem. John woont begeleid in een studio omdat alleen wonen geen optie meer is. De begeleiders daar zorgen er ook voor dat hij zijn medicatie neemt. Overdag gaat John naar Ter Motte, een zorginstelling aangepast voor mensen met jongdementie. Ze organiseren er verschillende activiteiten want hoe actiever de mensen zijn, hoe minder snel ze achteruit gaan.\nCindy gaat John elke vrijdag halen in Ter Motte. Ze doet hard haar best om voor hem te zorgen. Zijn kortetermijngeheugen is al aangetast, maar van zijn jeugd weet hij nog veel. Bij John is vooral zijn karakter veranderd door de ziekte. Hij was agressief en durfde ook seksueel getinte opmerkingen te maken naar vrouwen toe. Zijn remmingen vallen weg door de ziekte. Door de medicatie is dit intussen verbeterd.',
					premis_identifier: 'WP00178829',
					schema_genre: 'program',
					schema_date_published: '2020-09-01',
					schema_license: null,
					schema_date_created: '2020-09-01',
					schema_contributor: null,
					schema_maintainer: [{ schema_identifier: 'OR-rf5kf25' }],
					dcterms_format: 'video',
					schema_name: 'Durf te vragen R002 A0001',
				},
			},
			{
				_index: 'or-wd3q12h',
				_type: '_doc',
				_id: 's46h14z19k',
				_score: 1.0,
				_source: {
					schema_in_language: null,
					dcterms_available: '2019-10-07T10:39:06',
					schema_creator: { Archiefvormer: ['BRONKS'] },
					schema_identifier: 's46h14z19k',
					schema_description:
						'Videoclop "Plaisir a la mama", gemaakt door jongeren tijdens een BRONKS-workshop.',
					schema_publisher: null,
					schema_duration: '00:03:09',
					schema_abstract: null,
					premis_identifier: 'BE AMVB 326-1162-DAV',
					schema_genre: null,
					schema_date_published: null,
					schema_license: [
						'VIAA-PUBLIEK-METADATA-LTD',
						'VIAA-INTRA_CP-METADATA-ALL',
						'VIAA-INTRA_CP-CONTENT',
						'VIAA-ONDERZOEK',
						'VIAA-ONDERWIJS',
					],
					schema_date_created: null,
					schema_contributor: null,
					schema_maintainer: [{ schema_identifier: 'OR-wd3q12h' }],
					dcterms_format: 'video',
					schema_name: 'Plaisir a la mama, s.d. BRONKS',
				},
			},
		],
	},
};
