import type {
	InsertNotificationsMutation,
	UpdateNotificationMutation,
} from '~generated/graphql-db-types-hetarchief';

export enum NotificationStatus {
	UNREAD = 'UNREAD',
	READ = 'READ',
}

export enum NotificationType {
	VISIT_REQUEST_APPROVED = 'VISIT_REQUEST_APPROVED',
	VISIT_REQUEST_DENIED = 'VISIT_REQUEST_DENIED',
	NEW_VISIT_REQUEST = 'NEW_VISIT_REQUEST',
	VISIT_REQUEST_CANCELLED = 'VISIT_REQUEST_CANCELLED',
	ACCESS_PERIOD_VISITOR_SPACE_STARTED = 'ACCESS_PERIOD_VISITOR_SPACE_STARTED',
	ACCESS_PERIOD_VISITOR_SPACE_END_WARNING = 'ACCESS_PERIOD_VISITOR_SPACE_END_WARNING',
	ACCESS_PERIOD_VISITOR_SPACE_ENDED = 'ACCESS_PERIOD_VISITOR_SPACE_ENDED',
	MAINTENANCE_ALERT = 'MAINTENANCE_ALERT',
	NEW_MATERIAL_REQUEST = 'NEW_MATERIAL_REQUEST',
	MATERIAL_REQUEST_CANCELLED = 'MATERIAL_REQUEST_CANCELLED',
	MATERIAL_REQUEST_APPROVED = 'MATERIAL_REQUEST_APPROVED',
	MATERIAL_REQUEST_DENIED = 'MATERIAL_REQUEST_DENIED',
	MATERIAL_REQUEST_DOWNLOAD_AVAILABLE = 'MATERIAL_REQUEST_DOWNLOAD_AVAILABLE',
	MATERIAL_REQUEST_DOWNLOAD_ALMOST_EXPIRED = 'MATERIAL_REQUEST_DOWNLOAD_ALMOST_EXPIRED',
	MATERIAL_REQUEST_DOWNLOAD_EXECUTED = 'MATERIAL_REQUEST_DOWNLOAD_EXECUTED',
	MATERIAL_REQUEST_ADDITIONAL_CONDITIONS_SEND = 'MATERIAL_REQUEST_ADDITIONAL_CONDITIONS_SEND',
	MATERIAL_REQUEST_ADDITIONAL_CONDITIONS_ACCEPTED = 'MATERIAL_REQUEST_ADDITIONAL_CONDITIONS_ACCEPTED',
}

export interface Notification {
	description: string;
	title: string;
	id: string;
	status: NotificationStatus;
	visitId: string;
	createdAt: string;
	updatedAt: string;
	type: NotificationType;
	visitorSpaceSlug: string;
}

export type GqlNotification =
	| UpdateNotificationMutation['update_app_notification']['returning'][0]
	| InsertNotificationsMutation['insert_app_notification']['returning'][0];
