import {
	GetDctermsFormatDocument,
	GetHasCarrierDocument,
	GetHasPartDocument,
	GetIeObjectDocument,
	GetIsPartOfDocument,
	GetIsRepresentedByDocument,
	GetMeemooLocalIdDocument,
	GetMhFragmentIdentifierDocument,
	GetParentCollectionDocument,
	GetPremisIdentifierDocument,
	GetSchemaAlternateNameDocument,
	GetSchemaCopyrightHolderDocument,
	GetSchemaCreatorDocument,
	GetSchemaDurationDocument,
	GetSchemaGenreDocument,
	GetSchemaInLanguageDocument,
	GetSchemaIsPartOfDocument,
	GetSchemaKeywordsDocument,
	GetSchemaLicenseDocument,
	GetSchemaMediumDocument,
	GetSchemaPublisherDocument,
	GetSchemaSpatialDocument,
	GetSchemaTemporalDocument,
	GetSchemaThumbnailUrlDocument,
} from '~generated/graphql-db-types-hetarchief';

export const CACHE_KEY_PREFIX_IE_OBJECTS_SEARCH = 'ie-objects-find-all__';
export const CACHE_KEY_PREFIX_IE_OBJECT_DETAIL = 'ie-objects-find-one__';
export const CACHE_KEY_PREFIX_IE_OBJECT_THUMBNAIL = 'ie-objects-find-one-thumbnail__';

export const IE_OBJECT_DETAIL_QUERIES = [
	GetIeObjectDocument,
	GetDctermsFormatDocument,
	GetIsPartOfDocument,
	GetHasCarrierDocument,
	GetMeemooLocalIdDocument,
	GetPremisIdentifierDocument,
	GetMhFragmentIdentifierDocument,
	GetParentCollectionDocument,
	GetSchemaAlternateNameDocument,
	GetSchemaCopyrightHolderDocument,
	GetSchemaCreatorDocument,
	GetSchemaDurationDocument,
	GetSchemaGenreDocument,
	GetSchemaInLanguageDocument,
	GetSchemaIsPartOfDocument,
	GetSchemaKeywordsDocument,
	GetSchemaLicenseDocument,
	GetSchemaMediumDocument,
	GetSchemaPublisherDocument,
	GetSchemaSpatialDocument,
	GetSchemaTemporalDocument,
	GetSchemaThumbnailUrlDocument,
	GetHasPartDocument,
	GetIsRepresentedByDocument,
] as const;
